/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poro.gui;

import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poro.module.CalendarManager;
import poro.module.Session;
import poro.module.db.DatabaseManager;
import poro.module.db.data.MuonPhong;
import poro.module.db.data.Phong;
import poro.module.db.data.SinhVien;
import poro.module.db.data.TaiKhoan;
import poro.module.db.data.ThongTinMuonPhong;

/**
 *
 * @author ASUS
 */
public class MuonPhongJDialog extends javax.swing.JDialog {

    /**
     * Creates new form MuonPhongJDialog
     */
    public MuonPhongJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        pnlSinhVien.setVisible(chkMuonHo.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTenPhong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContent = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLau = new javax.swing.JTextField();
        txtMaPhong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTestTGBatDau = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTestTGKetThuc = new javax.swing.JTextField();
        btnDangKy2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtLyDo = new javax.swing.JTextField();
        chkMuonHo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtTGBatDau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTraDuKien = new javax.swing.JTextField();
        btnDangKy = new javax.swing.JButton();
        pnlSinhVien = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenSV = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng ký mượn phòng");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin phòng"));

        txtTenPhong.setEditable(false);

        jLabel3.setText("Tên phòng");

        tblContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên NM", "Bắt đầu", "Kết thúc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContent);

        jLabel4.setText("Danh sách mượn:");

        jLabel9.setText("Lầu");

        txtLau.setEditable(false);

        txtMaPhong.setEditable(false);

        jLabel10.setText("Mã phòng");

        jLabel11.setText("Thời gian bắt đầu");

        txtTestTGBatDau.setEditable(false);
        txtTestTGBatDau.setBackground(new java.awt.Color(255, 255, 255));
        txtTestTGBatDau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTestTGBatDauMouseClicked(evt);
            }
        });

        jLabel12.setText("Thời gian kết thúc");

        txtTestTGKetThuc.setEditable(false);
        txtTestTGKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        txtTestTGKetThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTestTGKetThucMouseClicked(evt);
            }
        });

        btnDangKy2.setText("Kiểm tra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtTestTGBatDau, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTenPhong, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTestTGKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(txtLau, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDangKy2)))
                                    .addComponent(jLabel12))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLau, txtMaPhong, txtTenPhong});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTestTGBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTestTGKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangKy2))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Đăng ký mượn"));

        jLabel8.setText("Lý do");

        chkMuonHo.setText("Tích vào đây nếu mượn phòng hộ");
        chkMuonHo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkMuonHoItemStateChanged(evt);
            }
        });

        jLabel1.setText("Thời gian bắt đầu");

        txtTGBatDau.setEditable(false);
        txtTGBatDau.setBackground(new java.awt.Color(255, 255, 255));
        txtTGBatDau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTGBatDauMouseClicked(evt);
            }
        });

        jLabel2.setText("Thời gian trả dự kiến");

        txtTraDuKien.setEditable(false);
        txtTraDuKien.setBackground(new java.awt.Color(255, 255, 255));
        txtTraDuKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTraDuKienMouseClicked(evt);
            }
        });

        btnDangKy.setText("Đăng ký mượn");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        jLabel5.setText("Mã SV");

        jLabel6.setText("Tên SV");

        jLabel7.setText("Email SV");

        javax.swing.GroupLayout pnlSinhVienLayout = new javax.swing.GroupLayout(pnlSinhVien);
        pnlSinhVien.setLayout(pnlSinhVienLayout);
        pnlSinhVienLayout.setHorizontalGroup(
            pnlSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTenSV)
            .addComponent(txtMaSV)
            .addComponent(txtEmail)
            .addGroup(pnlSinhVienLayout.createSequentialGroup()
                .addGroup(pnlSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlSinhVienLayout.setVerticalGroup(
            pnlSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSinhVienLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDangKy))
                    .addComponent(txtLyDo)
                    .addComponent(txtTraDuKien)
                    .addComponent(txtTGBatDau)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkMuonHo)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addComponent(pnlSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTGBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTraDuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkMuonHo)
                .addGap(18, 18, 18)
                .addComponent(pnlSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDangKy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTGBatDauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTGBatDauMouseClicked
        ChonNgayGioJDialog cngjd = new ChonNgayGioJDialog((JFrame) this.getParent(), true);
        cngjd.setDateOrigin(CalendarManager.getNow());
        cngjd.setVisible(true);
        txtTGBatDau.setText(cngjd.getResult());
    }//GEN-LAST:event_txtTGBatDauMouseClicked

    private void txtTraDuKienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTraDuKienMouseClicked
        ChonNgayGioJDialog cngjd = new ChonNgayGioJDialog((JFrame) this.getParent(), true);
        cngjd.setDateOrigin(CalendarManager.getNow());
        cngjd.setVisible(true);
        txtTraDuKien.setText(cngjd.getResult());
    }//GEN-LAST:event_txtTraDuKienMouseClicked

    private void chkMuonHoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkMuonHoItemStateChanged
        pnlSinhVien.setVisible(chkMuonHo.isSelected());
        txtMaSV.setText("");
        txtTenSV.setText("");
        txtEmail.setText("");
    }//GEN-LAST:event_chkMuonHoItemStateChanged

    private void txtTestTGBatDauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTestTGBatDauMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTestTGBatDauMouseClicked

    private void txtTestTGKetThucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTestTGKetThucMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTestTGKetThucMouseClicked

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        try {
            insert();
            JOptionPane.showMessageDialog(this, "Mượn phòng thành công");
            this.dispose();
        } catch (ToViewException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuonPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuonPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuonPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuonPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MuonPhongJDialog dialog = new MuonPhongJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangKy2;
    private javax.swing.JCheckBox chkMuonHo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlSinhVien;
    private javax.swing.JTable tblContent;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLau;
    private javax.swing.JTextField txtLyDo;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTGBatDau;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JTextField txtTenSV;
    private javax.swing.JTextField txtTestTGBatDau;
    private javax.swing.JTextField txtTestTGKetThuc;
    private javax.swing.JTextField txtTraDuKien;
    // End of variables declaration//GEN-END:variables

    ArrayList<ThongTinMuonPhong> ttmps = new ArrayList<>();

    public void loading(int soTang, int idPhong) {
        ThongTinMuonPhong ttmp = new ThongTinMuonPhong();
        ttmp.setSoTang(soTang);
        ttmp.setIdPhong(idPhong);
        ttmps = DatabaseManager.executeQuery(ttmp, ThongTinMuonPhong.EXECUTE_SELECT_BY_ID_PHONG);
        if (ttmps == null || ttmps.isEmpty()) {
            return;
        }
        Phong p = ttmps.get(0).getPhong();
        txtLau.setText(p.getIdSoTang() + "");
        txtMaPhong.setText(p.getIdPhong() + "");
        txtTenPhong.setText(p.getTenPhong());
        DefaultTableModel dtm = (DefaultTableModel) tblContent.getModel();
        dtm.setRowCount(0);
        ttmps.forEach(tt -> {
            if (tt.getPhong().getLuotDat() >= 0 && tt.getMuonPhong() != null && tt.getMuonPhong().getTgTraThucTe() == null) {
                dtm.addRow(new Object[]{
                    tt.getTaiKhoan().getTen() + " (" + tt.getTaiKhoan().getIdTaiKhoan() + ")",
                    CalendarManager.getString(tt.getMuonPhong().getTgMuon(), CalendarManager.DATE_HOUR_FULL_FORMAT),
                    CalendarManager.getString(tt.getMuonPhong().getTgMuon(), CalendarManager.DATE_HOUR_FULL_FORMAT)
                });
            }
        });
    }

    public void reset() {
        txtTGBatDau.setText("");
        txtTraDuKien.setText("");
        txtLyDo.setText("");
        txtMaSV.setText("");
        txtTenSV.setText("");
        txtEmail.setText("");
    }

    private Form getForm() {
        Form form = new Form();

        TaiKhoan tk = Session.USER;
        int soTang = Integer.parseInt(txtLau.getText());
        int idPhong = Integer.parseInt(txtMaPhong.getText());
        Date tgMuon = CalendarManager.getDateByString(txtTGBatDau.getText(), CalendarManager.DATE_HOUR_FULL_FORMAT);
        Date tgTra = CalendarManager.getDateByString(txtTraDuKien.getText(), CalendarManager.DATE_HOUR_FULL_FORMAT);
        String lyDo = txtLyDo.getText();
        form.muonPhong = new MuonPhong(-1, tk.getIdTaiKhoan(), soTang, idPhong, tgMuon, tgTra, null, lyDo);

        String idSv = txtMaSV.getText().trim();
        String email = txtEmail.getText().trim();
        String tenSv = txtTenSV.getText().trim();
        form.sinhVien = new SinhVien(idSv, email, tenSv, -1);
        return form;
    }

    private void insert() throws ToViewException {
        Form form = getForm();
        int ok = DatabaseManager.executeUpdate(form.muonPhong, MuonPhong.EXECUTE_INSERT);
        if (ok <= 0) {
            throw new ToViewException("Mượn phòng thất bại");
        }
        
        if (!chkMuonHo.isSelected()){
            return;
        }
        
        int idMuon = DatabaseManager.executeQuery(form.muonPhong, MuonPhong.EXECUTE_SELECT_LAST_INSERT).get(0).getIdMuonPhong();
        
        form.sinhVien.setIdMuonPhong(idMuon);
        DatabaseManager.executeUpdate(form.sinhVien, SinhVien.EXECUTE_INSERT);
    }

    private class Form {

        MuonPhong muonPhong;
        SinhVien sinhVien;
    }
}
