/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poro.gui;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author ASUS
 */
public class QLMainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public QLMainJFrame() {
        initComponents();
        
        setGiaoDien(false);
    }

    /**
     * Thêm một tab vào màn hình chính
     */
    private void addTab(String title, JPanel panel) {
        JScrollPane jb = new JScrollPane();
        jb.setBorder(null);
        jb.setViewportView(panel);
        jb.setBorder(javax.swing.BorderFactory.createEtchedBorder(Color.BLACK, null));
        tblContent.addTab(title, jb);
    }

    /**
     * Chuyển đổi giao diện cho người mượn hoặc quản lý
     * 
     * @param chucVu Chức vụ sẽ hiện (true là quản lý)
     */
    private void setGiaoDien(boolean chucVu){
        mniQLTaiKhoan.setVisible(chucVu);
        mniXemTaiKhoan.setVisible(chucVu);
        mniXemPhong.setVisible(chucVu);
        mniXemPhong.setVisible(chucVu);
        mniQLPhong.setVisible(chucVu);
        mnuThongKe.setVisible(chucVu);
        btnQuanLyPhong.setVisible(chucVu);
        btnQuanLyTaiKhoan.setVisible(chucVu);
        btnThongKe.setVisible(chucVu);
        sptMnuSauQLTaiKhoan.setVisible(chucVu);
        sptSauThongKe.setVisible(chucVu);
        btnMuonPhong.setVisible(!chucVu);
        mniMuonPhong.setVisible(!chucVu);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        toolbar = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        sptSauTaiKhoan = new javax.swing.JToolBar.Separator();
        btnQuanLyTaiKhoan = new javax.swing.JButton();
        btnQuanLyPhong = new javax.swing.JButton();
        btnMuonPhong = new javax.swing.JButton();
        sptSauPhong = new javax.swing.JToolBar.Separator();
        btnThongKe = new javax.swing.JButton();
        sptSauThongKe = new javax.swing.JToolBar.Separator();
        btnThoat = new javax.swing.JButton();
        tblContent = new javax.swing.JTabbedPane();
        scrTrangChu = new javax.swing.JScrollPane();
        pnlTrangChu = new javax.swing.JPanel();
        pnlChanTrang = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mnubar = new javax.swing.JMenuBar();
        mnuTaiKhoan = new javax.swing.JMenu();
        mniQLTaiKhoan = new javax.swing.JMenuItem();
        mniXemTaiKhoan = new javax.swing.JMenuItem();
        sptMnuSauQLTaiKhoan = new javax.swing.JPopupMenu.Separator();
        mniDangNhap = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        sptMnuSauTaiKhoan = new javax.swing.JPopupMenu.Separator();
        mniThoat = new javax.swing.JMenuItem();
        mnuPhong = new javax.swing.JMenu();
        mniQLPhong = new javax.swing.JMenuItem();
        mniXemPhong = new javax.swing.JMenuItem();
        mniMuonPhong = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniThongKePhong = new javax.swing.JMenuItem();
        mniThongKeGv = new javax.swing.JMenuItem();
        mniThongKeAll = new javax.swing.JMenuItem();
        mnuGioiThieu = new javax.swing.JMenu();
        mniChungToi = new javax.swing.JMenuItem();
        mniHuongDan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PolyRoom - Quản Lí Phòng Học");

        toolbar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        toolbar.setRollover(true);
        toolbar.setMargin(new java.awt.Insets(5, 5, 5, 5));

        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnDangXuat);

        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.setFocusable(false);
        btnDoiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoiMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnDoiMatKhau);
        toolbar.add(sptSauTaiKhoan);

        btnQuanLyTaiKhoan.setText("Quản lý tài khoản ");
        btnQuanLyTaiKhoan.setFocusable(false);
        btnQuanLyTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnQuanLyTaiKhoan);

        btnQuanLyPhong.setText("Quản lý phòng");
        btnQuanLyPhong.setFocusable(false);
        btnQuanLyPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnQuanLyPhong);

        btnMuonPhong.setText("Mượn phòng");
        btnMuonPhong.setFocusable(false);
        btnMuonPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMuonPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnMuonPhong);
        toolbar.add(sptSauPhong);

        btnThongKe.setText("Thống kê");
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnThongKe);
        toolbar.add(sptSauThongKe);

        btnThoat.setText("Thoát");
        btnThoat.setFocusable(false);
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnThoat);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        scrTrangChu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        javax.swing.GroupLayout pnlTrangChuLayout = new javax.swing.GroupLayout(pnlTrangChu);
        pnlTrangChu.setLayout(pnlTrangChuLayout);
        pnlTrangChuLayout.setHorizontalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        pnlTrangChuLayout.setVerticalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        scrTrangChu.setViewportView(pnlTrangChu);

        tblContent.addTab("Trang chủ", scrTrangChu);

        getContentPane().add(tblContent, java.awt.BorderLayout.CENTER);

        pnlChanTrang.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Đây là chân trang");
        pnlChanTrang.add(jLabel7, java.awt.BorderLayout.LINE_END);

        jLabel8.setText("Đây cũng là chân trang");
        pnlChanTrang.add(jLabel8, java.awt.BorderLayout.LINE_START);

        getContentPane().add(pnlChanTrang, java.awt.BorderLayout.PAGE_END);

        mnuTaiKhoan.setText("Tài khoản");

        mniQLTaiKhoan.setText("Quản lí tài khoản");
        mnuTaiKhoan.add(mniQLTaiKhoan);

        mniXemTaiKhoan.setText("Xem tài khoản");
        mnuTaiKhoan.add(mniXemTaiKhoan);
        mnuTaiKhoan.add(sptMnuSauQLTaiKhoan);

        mniDangNhap.setText("Đăng nhập");
        mnuTaiKhoan.add(mniDangNhap);

        mniDangXuat.setText("Đăng xuất");
        mnuTaiKhoan.add(mniDangXuat);
        mnuTaiKhoan.add(sptMnuSauTaiKhoan);

        mniThoat.setText("Thoát");
        mnuTaiKhoan.add(mniThoat);

        mnubar.add(mnuTaiKhoan);

        mnuPhong.setText("Phòng");

        mniQLPhong.setText("Quản lí phòng");
        mnuPhong.add(mniQLPhong);

        mniXemPhong.setText("Xem phòng");
        mnuPhong.add(mniXemPhong);

        mniMuonPhong.setText("Mượn phòng");
        mnuPhong.add(mniMuonPhong);

        mnubar.add(mnuPhong);

        mnuThongKe.setText("Thống kê");

        mniThongKePhong.setText("Thống kê phòng");
        mnuThongKe.add(mniThongKePhong);

        mniThongKeGv.setText("Thống kê giảng viên");
        mnuThongKe.add(mniThongKeGv);

        mniThongKeAll.setText("Thống kê tất cả");
        mnuThongKe.add(mniThongKeAll);

        mnubar.add(mnuThongKe);

        mnuGioiThieu.setText("Giới thiệu");

        mniChungToi.setText("Về chúng tôi");
        mnuGioiThieu.add(mniChungToi);

        mniHuongDan.setText("Hướng dẫn");
        mnuGioiThieu.add(mniHuongDan);

        mnubar.add(mnuGioiThieu);

        setJMenuBar(mnubar);

        setSize(new java.awt.Dimension(985, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnMuonPhong;
    private javax.swing.JButton btnQuanLyPhong;
    private javax.swing.JButton btnQuanLyTaiKhoan;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem mniChungToi;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniMuonPhong;
    private javax.swing.JMenuItem mniQLPhong;
    private javax.swing.JMenuItem mniQLTaiKhoan;
    private javax.swing.JMenuItem mniThoat;
    private javax.swing.JMenuItem mniThongKeAll;
    private javax.swing.JMenuItem mniThongKeGv;
    private javax.swing.JMenuItem mniThongKePhong;
    private javax.swing.JMenuItem mniXemPhong;
    private javax.swing.JMenuItem mniXemTaiKhoan;
    private javax.swing.JMenu mnuGioiThieu;
    private javax.swing.JMenu mnuPhong;
    private javax.swing.JMenu mnuTaiKhoan;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenuBar mnubar;
    private javax.swing.JPanel pnlChanTrang;
    private javax.swing.JPanel pnlTrangChu;
    private javax.swing.JScrollPane scrTrangChu;
    private javax.swing.JPopupMenu.Separator sptMnuSauQLTaiKhoan;
    private javax.swing.JPopupMenu.Separator sptMnuSauTaiKhoan;
    private javax.swing.JToolBar.Separator sptSauPhong;
    private javax.swing.JToolBar.Separator sptSauTaiKhoan;
    private javax.swing.JToolBar.Separator sptSauThongKe;
    private javax.swing.JTabbedPane tblContent;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
