package poro.gui;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import poro.dao.DatabaseManager;
import poro.dao.data.TaiKhoan;
import poro.module.Mailer;
import poro.module.StringHelper;

/**
 *
 * @author Cô Ngọc
 */
public class QuenMatKhauJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuenMatKhau
     */
    public QuenMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        doiMatKhauJDialog = new DoiMatKhauJDialog(parent, true);
    }

    private DoiMatKhauJDialog doiMatKhauJDialog;

    private static String otp = "";
    TaiKhoan tk = new TaiKhoan();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnGuiMa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaOTP = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        hinh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quên mật khẩu");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nhập email tài khoản của bạn");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, 50));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 420, 30));

        btnGuiMa.setText("Gửi mã OTP");
        btnGuiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiMaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nhập mã OTP của bạn");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        getContentPane().add(txtMaOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 420, 30));

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        getContentPane().add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 110, 30));

        hinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/br1.jpg"))); // NOI18N
        getContentPane().add(hinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiMaActionPerformed
        try {
            // TODO add your handling code here:
            guiOTP();
            JOptionPane.showMessageDialog(this, "Đã gửi mã OTP vui lòng kiểm tra email!");
        } catch (ToViewException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnGuiMaActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        xacNhan();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhauJDialog dialog = new QuenMatKhauJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiMa;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel hinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtMaOTP;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables

    private void guiOTP() throws ToViewException {
        if (!otp.isEmpty()) {
            throw new ToViewException("Đã gửi mã OTP rồi vui lòng kiểm tra lại email!");
        }
        if (!txtemail.getText().matches("\\w+(\\.\\w+)*@\\w+(\\.\\w+)+")) {
            throw new ToViewException("Email không đúng định dạng!");
        }
        
        tk.setEmail(txtemail.getText().trim());
        
        ArrayList<TaiKhoan> tkList = DatabaseManager.executeQuery(tk, TaiKhoan.EXECUTE_SELECT_BY_MAIL);

        if (tkList.size() <= 0) {
            throw new ToViewException("Không tồn tại tài khoản có email " + tk.getEmail());
        }

        StringHelper sh = new StringHelper();
        otp = sh.random(6);
        tk = tkList.get(0);

        Mailer mailer = new Mailer(tk.getEmail());
        mailer.setSubject("Quên mật khẩu - PolyRoom");
        mailer.setText("Mã OTP của bạn là: " + otp);
        new Thread(mailer).start();
    }

    private void xacNhan() {
        if (otp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có mã OTP gửi đến email của bạn!");
            return;
        }
        if (txtMaOTP.getText().equals(otp)) {
            otp = "";
            doiMatKhauJDialog.setTaiKhoanDMK(tk);
            doiMatKhauJDialog.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Mã OTP sai!");
        }
    }

}
